S03 us02
WildCodeSchool-2023-09/JS-RemoteFR-SACOD-P2-Vogue-Merry pull request #55
Opened 2023-10-30 17:28 UTC by Enagrom5

ajout des boutons ingrédients mais pour le moment il peut y avoir des doublons. A corriger dans une prochaine user story.

2023-10-30 17:58 UTC, BarisRz requested changes
Des petits changements a faire pour pas compliquer la dev (pour les conflits) mais sinon le reste est top 👌

2023-10-30 17:58 UTC, BarisRz commented on frontend/src/pages/ErrorPage.jsx
> -        <i>{error.error.message || "Erreur"}</i>
Ici le error.error est nécessaire car sinon ça renvoie "undefined"

2023-10-30 17:58 UTC, BarisRz commented on frontend/src/main.jsx
> +      },
Ici faudrait supprimé c'est ligne pour éviter les conflits du router, ceux de la dev amène déjà a tout le site

2023-10-30 19:30 UTC, Hkaiser45 approved these changes
ok, apres changement

2023-10-31 07:49 UTC, BarisRz approved these changes
Top Morgane 🥳

2023-10-31 10:38 UTC, GorskiAnthony commented on frontend/src/components/Ingrédients.jsx
Le nom du fichier c'est bien `Ingrédients` ??? Avec un `é` ????

2023-10-31 10:42 UTC, Enagrom5 commented on frontend/src/components/Ingrédients.jsx
changé

2023-10-31 10:43 UTC, merged